<script type="text/x-magento-init">
    {
        "*": {
			"TealiumTagsUtagLib": "<?php echo $block->getJsLayout();?>",
            "TealiumTagsUtagJs": "<?php echo $block->getJsLayout();?>",
            "TealiumTagsMiniCart":"<?php echo $block->getJsLayout();?>",
            "TealiumTagsPaymentMethod": "<?php echo $block->getJsLayout();?>",
            "TealiumTagsUserLogout": "<?php echo $block->getJsLayout();?>"
        }
    }
</script>