<script type="text/x-magento-init">
{
  "*": {
    "Tealium_Tags/js/utagLib": <?= /* @noEscape */ $block->getJsLayout(); ?>,
    "Tealium_Tags/js/myUtag": <?= /* @noEscape */ $block->getJsLayout(); ?>,
    "Tealium_Tags/js/miniCart": <?= /* @noEscape */ $block->getJsLayout(); ?>,
    "Tealium_Tags/js/extendPaymentMethod": <?= /* @noEscape */ $block->getJsLayout(); ?>,
    "Tealium_Tags/js/userLogout": <?= /* @noEscape */ $block->getJsLayout(); ?>
  }
}
</script>
