<?php

$helper = Mage::helper('tealium_tags');
$store = Mage::app()->getStore();

// if Tealium extension is not enabled, return immediately to not render
if (!$helper->isEnabled($store)) {
    return; // not enabled, no javascript inserted
}

// get the terms used
$terms = array();

if (sizeof($this->getTerms()) > 0) {
    foreach ($this->getTerms() as $_term) {
        $terms[] = $_term->getName();
    }
} else {
    $terms[] = "no-terms";
}

// initialize the custom data with popular search terms
$customData = array();
$customData["page_type"] = "popular search terms";
$customData["page_name"] = $this->getLayout()->getBlock('head')->getTitle();
$customData["search_keyword"] = implode('","', $terms);

// create a tealium object for the page
$tealium = $helper->init($store, $this, "Search")
    ->addCustomDataFromSetup($store, "Search")
    ->addCustomDataFromObject($customData)
    ->getTealiumObject();

// load and use the external config if it's enabled
if ($helper->getIsExternalScript($store)) {
    $syncType = "sync";
    $externalScriptType = $helper->getExternalScriptType($store);
    if ($externalScriptType == "sync" || $externalScriptType == "async") {
        $syncType = $externalScriptType;
    }
    echo $tealium->render("full", true, $syncType);
} else {
    echo $tealium->render("udo");
}

// Sometimes it's useful to send the entire udo to a server for diagnostics.
// Render a tag in the form of an html <img> element that
// will send the url encoded udo to a specified server if the feature is
// enabled in the config.
echo $helper->getDiagnosticTag($store);
